# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-09 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico', models.CharField(max_length=250)),
                ('data_emissao', models.CharField(max_length=25)),
                ('texto_receita', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_remedio', models.CharField(max_length=250)),
                ('texto_remedio', models.CharField(max_length=10000)),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.Prescricao')),
            ],
        ),
    ]
