# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-16 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_auto_20190616_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescricao',
            name='remedio1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receitas.Remedio'),
        ),
    ]
