# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-16 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_prescricao_remedio1'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescricao',
            name='remedio2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedio2s', to='receitas.Remedio'),
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='remedio1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedio1s', to='receitas.Remedio'),
        ),
    ]
