# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-16 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_auto_20190616_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescricao',
            name='remedio3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedio3s', to='receitas.Remedio'),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='remedio4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedio4s', to='receitas.Remedio'),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='remedio5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedio5s', to='receitas.Remedio'),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='remedio6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedio6s', to='receitas.Remedio'),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='remedio7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedio7s', to='receitas.Remedio'),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='remedio8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedio8s', to='receitas.Remedio'),
        ),
    ]
