# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-16 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_auto_20190616_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='texto_receita',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='remedio',
            name='texto_remedio',
            field=models.TextField(),
        ),
    ]
