# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-16 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_auto_20190616_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedio',
            name='nome_remedio',
            field=models.CharField(default='()_Sem Remédio', max_length=250),
        ),
    ]
