# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-16 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0008_remedio_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedio',
            name='is_favorite',
        ),
    ]
